### ISSUE TITLE
WordPress RokStories documentation missing 

### ISSUE THREAD

**Issue by kat05** [rockettheme/docs#252]
It is listed as available here:
http://www.rockettheme.com/docs/wordpress

But the link is dead:
http://www.rockettheme.com/docs/wordpress/plugins/rokstories

**Comment by FrugalGeek** [comment]
Closing this one after removing RokStories from the index. Since RokStories is legacy, we no longer actively support it at a level where documentation would be maintained. We went through and killed a few extensions/plugins from documentation not long ago, this might have been one of them or an oversight when the index was created. Thanks!
